steps:

  - key: "asterius-dev-image"
    label: "asterius-dev-image"
    command: |
      mkdir /tmp/asterius
      mv .buildkite/* /tmp/asterius
      git checkout -f master
      mv /tmp/asterius/* .buildkite
      rm -rf /tmp/asterius

      docker pull debian:sid
      docker build \
        --compress \
        --file dev.Dockerfile \
        --label "gitrev=$(git rev-parse HEAD)" \
        --network host \
        --no-cache \
        --squash \
        --tag terrorjack/asterius:dev \
        .
      nix-shell \
        .buildkite/shell.nix \
        --command "docker save terrorjack/asterius:dev | zstd -T8 --ultra -22 -o /tmp/asterius-dev-image.tar.zst"
      buildkite-agent artifact upload /tmp/asterius-dev-image.tar.zst
      rm /tmp/asterius-dev-image.tar.zst
      docker system prune --all --force
