steps:

  - key: "asterius-image"
    label: "asterius-image"
    command: |
      mkdir /tmp/asterius
      mv * /tmp/asterius
      git checkout -f master
      mv /tmp/asterius/* .
      rm -rf /tmp/asterius

      docker system prune --all --force
      docker pull terrorjack/asterius:base
      docker build \
        --build-arg jobs=8 \
        --compress \
        --file stackage.Dockerfile \
        --label "gitrev=$(git rev-parse HEAD)" \
        --network host \
        --no-cache \
        --squash \
        --tag terrorjack/asterius \
        .
      docker run --rm terrorjack/asterius ahc-pkg list > /tmp/asterius-image.txt
      buildkite-agent artifact upload /tmp/asterius-image.txt
      docker system prune --all --force
